### ISSUE TITLE
Install Operator and test private link CRD (spike/exploration)

### ISSUE THREAD

**Issue by Richard87** [equinor/radix-platform#1271]
Steps:
- Install ASO
- Add resoruces under
- enjoy:
   ```
   $ getent hosts sqlserver-dev
   10.0.0.10       sqlserver-dev.edc2023-radix-wi-rihag-dev.svc.cluster.local
   ```

In this scenario, what we need from the user is:
- internal dns name (sqlserver-dev)
- groupIds (sqlServer)
- resource id ` /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/vulnerability-scan-dev/providers/Microsoft.Sql/servers/sql-radix-vulnerability-scan-dev`
- Manually approval

# Thoughts
- Any duplicate private endpoints will override existing DNS records, so when deleting one, the previous one will also stop working
- Should we use private dns (available for all radix applications) or manage our own services like below?
- If custom services, how do we handle resources with multiple domains/ips? Like storage accounts or registries? Maybe we can use `ipConfigurations`, ref discussion in this issue: https://github.com/Azure/azure-service-operator/issues/3901

```yaml
apiVersion: network.azure.com/v1api20220701
kind: PrivateEndpoint
metadata:
  namespace: edc2023-radix-wi-rihag-app
  name: pe-sqlserver-dev
spec:
  location: northeurope
  # pe-radix-<APP-NAME>-<INTERNAL-DNS-NAME>
  azureName: pe-radix-edc2023-radix-wi-rihag-sqlserver-dev

  subnet:
    reference:
      armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/cluster-vnet-hub-dev/providers/Microsoft.Network/virtualNetworks/vnet-hub/subnets/private-links


  owner:
    armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/cluster-vnet-hub-dev

  manualPrivateLinkServiceConnections:
    - groupIds:
        - sqlServer
      name: pe-radix-edc2023-radix-wi-rihag-sqlserver-dev
      requestMessage: RIHAG@EQUINOR.COM Requests a connection to Omnia Radix
      privateLinkServiceReference:
        armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/vulnerability-scan-dev/providers/Microsoft.Sql/servers/sql-radix-vulnerability-scan-dev
---
apiVersion: v1
kind: Service
metadata:
  namespace: edc2023-radix-wi-rihag-dev
  name: sqlserver-dev
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: edc2023-radix-wi-rihag-dev
  name: sqlserver-dev
subsets:
  - addresses:
      - ip: 10.0.0.10 # From status in Private Endpoint CRD after it has been approved

```

This works to create new Private Endpoints, with Private DNS Zone config:
```yaml
apiVersion: network.azure.com/v1api20220701
kind: PrivateEndpoint
metadata:
  name: pe-sqlserver-dev
  namespace: edc2023-radix-wi-rihag-app
spec:
  location: northeurope
  # pe-radix-<APP-NAME>-<INTERNAL-DNS-NAME>
  azureName: pe-radix-edc2023-radix-wi-rihag-sqlserver-dev

  subnet:
    reference:
      armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/cluster-vnet-hub-dev/providers/Microsoft.Network/virtualNetworks/vnet-hub/subnets/private-links


  owner:
    armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/cluster-vnet-hub-dev

  manualPrivateLinkServiceConnections:
    - groupIds:
        - sqlServer
      name: pe-radix-edc2023-radix-wi-rihag-sqlserver-dev
      requestMessage: RIHAG@EQUINOR.COM Requests a connection to Omnia Radix
      privateLinkServiceReference:
        armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/vulnerability-scan-dev/providers/Microsoft.Sql/servers/sql-radix-vulnerability-scan-dev
---
apiVersion: network.azure.com/v1api20220701
kind: PrivateEndpointsPrivateDnsZoneGroup
metadata:
  name: pe-dns-sqlserver-dev
  namespace: edc2023-radix-wi-rihag-app
spec:
  owner:
    name: pe-sqlserver-dev
  privateDnsZoneConfigs:
    - name: pe-radix-edc2023-radix-wi-rihag-sqlserver-dev # Where is this name used?
      privateDnsZoneReference:
        armId: /subscriptions/16ede44b-1f74-40a5-b428-46cca9a5741b/resourceGroups/cluster-vnet-hub-dev/providers/Microsoft.Network/privateDnsZones/privatelink.database.windows.net

```
