### ISSUE TITLE
Investigate how Kubernetes handles pods that exceed emptyDir sizeLimit

### ISSUE THREAD

**Issue by nilsgstrabo** [equinor/radix-platform#1309]
When a container exceeds memory limits, Kubernetes kills the container (OOMKilled) and starts a new container in the same Pod. The containerStatus restartCount is increased, and we show this info in web console.

When a container exceeds an emptyDir sizeLimit, it seems the behaviour is different. Instead of killing and restarting the container in the same Pod, Kubernetes sends a SIGTERM signal, allowing the application to gracefully shut down. When the container exits, Kubernetes creates a new Pod instaead of "reusing" the existing Pod. The "old" Pod status is set to Completed, and there is no info ion the status object that the Pod was told to stop because ity exceeded sizeLimit of emptyDir

**Comment by nilsgstrabo** [comment]
When a pod exceeds the emptyDir sizeLimit, the pod is forcefully terminated with status.Phase=Failed, status.Reason=Evicted and status.message='Usage of EmptyDir volume "radix-vm-tmp" exceeds the limit "5M". '
The Pod is not deleted, but is kept for information.

Example:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-23T11:26:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-23T11:28:42Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-23T11:28:42Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-23T11:26:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://ae1a03c55355b5f5bc29b6c6990727ee87a6d8b845e2d8a795487d78bc193712
    image: radixdev.azurecr.io/oauth-demo-dev-simple:e2pmj
    imageID: radixdev.azurecr.io/oauth-demo-dev-simple@sha256:ce0827dd93e2dc2d96ac7a941cc2bbf9687ec5e93a8c8218a1d90784c8484859
    lastState: {}
    name: simple
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://ae1a03c55355b5f5bc29b6c6990727ee87a6d8b845e2d8a795487d78bc193712
        exitCode: 137
        finishedAt: "2024-04-23T11:28:42Z"
        reason: Error
        startedAt: "2024-04-23T11:26:41Z"
  hostIP: 10.5.3.108
  message: 'Usage of EmptyDir volume "radix-vm-tmp" exceeds the limit "5M". '
  phase: Failed
  podIP: 10.5.3.130
  podIPs:
  - ip: 10.5.3.130
  qosClass: Burstable
  reason: Evicted
  startTime: "2024-04-23T11:26:40Z"
```

Currently, this info is not shown to the user in Radix Web Console.
