### ISSUE TITLE
Enable Observability (Cilium) for AKS (Advanced Container Networking)

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-platform#1371]
Enable in **dev** **first**

Add in Terraform AKS enable add-on
- Cilium
- Advanced Container Networking

Example network policy to obtain DNS names for requests to "world":

```
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "tofqdn-dns-visibility"
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - world

```

# TODO:
- Ask Microsoft if Cilium is supported on ARM or not, ref. https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#upgrade-an-existing-cluster-to-cni-overlay 
Not an issue

**DoD**
Ready to be enabled in Prod clusters
