### ISSUE TITLE
Environmental dependent components

### ISSUE THREAD

**Issue by Christdej** [equinor/radix-platform#239]
We have the following issue:

Some components we are only interested in deploying to one environment. Take this example code from radixconfig.yaml:

```
components:
   - name: grafana
     src: monitoring/grafana
     secrets:
       - GF_SECURITY_ADMIN_PASSWORD
     ports:
       - name: http
         port: 3000
     publicPort: http
```

Here, the folder "monitoring/grafana" is only present in one of our branches, and hence we only want to deploy this component for the environment based on that branch. But this will fail for all environments that do not have the required folders/files.
 "ERROR: '/workspace/monitoring/grafana/' is not a valid remote URL for git or tarball."

Thanks for your help,
Christian de Jonge
Software Innovation Bergen
