### ISSUE TITLE
Support of the command keyword in components

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/radix-platform#368]
**Is your feature request related to a problem? Please describe.**
Sometimes, it might be desirable not to have to give each docker container a default command to execute, but rather explicitly state the command in `radixconfig.yaml`, as can be done in helm charts, and in docker compose.

**Describe the solution you'd like**
```yaml
spec:
  environments:
    - name: prod
      build:
        from: master
  components:
    - name: api
      ...
      command: flask run

    - name: web
      ...
      command: serve
```

**Describe alternatives you've considered**
Using the default command (i.e. `CMD`), by defining it in the relevant `Dockerfile`s

**Additional context**
#367 would also implement this.
Additionally, having the `command` keyword available, would make it easier to generate `radixconfig.yaml` from `docker-compose.yaml`, so that it's easier to have a single source of truth.
