### ISSUE TITLE
Reuse configuration between components

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/radix-platform#370]
**Is your feature request related to a problem? Please describe.**
When I want different image tags for different environments, I must duplicate a lot of configuration for each component;

```yaml
components:
  - name: proxy
    image: nginx
    alwaysPullImageOnDeploy: true

  - name: web
    image: some.container.registry/project/web:{imageTag}
    alwaysPullImageOnDeploy: true
    environmentConfig:
    - environment: dev
      imageTag: latest
    - environment: release
      imageTag: release
    - environment: feature
      imageTag: feature

  - name: api
    image: some.container.registry/project/api:{imageTag}
    alwaysPullImageOnDeploy: true
    environmentConfig:
    - environment: dev
      imageTag: latest
    - environment: release
      imageTag: release
    - environment: feature
      imageTag: feature
...
```

**Describe the solution you'd like**

I'd like to be able to use YAML anchors, and aliases;

```yaml
x-always-pull: &always-pull
  alwaysPullImageOnDeploy: true

x-use-tags: &use-tags
  <<: *always-pull
  environmentConfig:
    - environment: dev
      imageTag: latest
    - environment: release
      imageTag: release
    - environment: feature
      imageTag: feature


components:
  - name: proxy
    image: nginx
    <<: *always-pull

  - name: web
    image: some.container.registry/project/web:{imageTag}
    <<: *use-tags

  - name: api
    image: some.container.registry/project/api:{imageTag}
    <<: *use-tags
...
```

or similar.

An alternative could be to include a common component configuration tag.

**Describe alternatives you've considered**

Copy/paste configuration

**Additional context**

The use case, is to have different docker images for each environment.
The images are build elsewhere.
