### ISSUE TITLE
Add support for specifying a port range in the configuration

### ISSUE THREAD

**Issue by sindre-nistad** [equinor/radix-platform#407]
**Is your feature request related to a problem? Please describe.**
In my particular case, the issue arise when we use the [py4j package](https://www.py4j.org) to facilitate communication between Python and Java. The package opens (at least) two ports (for transmitting, and receiving) inside the container. These ports are semi-random, and there does not seem to be an easy way to explicitly set them.
Additionally, these ports are opened / created per thread / invocation. This means that for a [Flask server](https://flask.palletsprojects.com/en/1.1.x/) there may be many ports opened.

**Describe the solution you'd like**
Be able to specify
```yaml
...
  components:
    - name: api
      src: .
      ports:
        - name: http
          port: 5000
        - name: py4j
          port: "32000-65000"
      publicPort: http
...
```

**Describe alternatives you've considered**
A workaround, would be to specify each possible port (presumably generated from a small script).

**Additional context**
