### ISSUE TITLE
Add a TriggerPipeline setting to radix-config 

### ISSUE THREAD

**Issue by AndreaEsposit** [equinor/radix-platform#608]
As of now, there is no out-of-the-box method to remove the autobuild feature for one specific branch/radix-enviroment, while also be able to build manually from that branch. 

A new "triggerPipeline" propriety for a branch in  a specific env (like "master" for qa in the example below), would give an easy way to remove the default behavior for a specific env.

```   
    - name: qa
      build:
        from: master
        triggerPipeline: false
    - name: dev
      build:
        from: master 
```

For the time being, I've been advised to remove a webhook and replace it with a GitHub action that starts the build-deploy operation with Radix CLI to commit to particular branches. This is possibly a solution, but is much less straight forward than the "triggerPipeline" propriety.
