### ISSUE TITLE
Allow specifying container registry per environment

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-platform#627]
**Is your feature request related to a problem? Please describe.**
At the moment we need to define the registry on the component-level in radix-config, but we would like to use separate registries for our environments (dev/qa/prod) to keep everything as separate as possible

**Describe the solution you'd like**
Now:
```yml
  components:
    - name: app
      image: topsrvregistrydev.azurecr.io/tops-rv/app:{imageTagName}
      environmentConfig:
        - environment: qa
          imageTagName: qa
```

What I would like to see:
```yml
  environments:
    - name: qa
      containerRegistry: myRegistryQa.azurecr.io
    - name: prod
      containerRegistry: myRegistryProd.azurecr.io
  components:
    - name: app
      image: repo/app:{imageTagName}
      environmentConfig:
        - environment: qa
          imageTagName: qa
```

**Describe alternatives you've considered**
It is possible to do something like this:
```yml
  components:
    - name: app
      image: {imageTagName}
      environmentConfig:
        - environment: qa
          imageTagName: myRegistryQa.azurecr.io/repo/app:qa
```

**Comment by emirgens** [comment]
You can in fact specify the whole string for the image in the env.config section. (Maybe not the completely correct naming for the variable), however it works! This can be combined with the use of yaml anchors.

**Sample**: 
```
  components:
    - name: app
      image: {imageTagName}
      environmentConfig:
        - environment: qa
          imageTagName: topsrvregistrydqa.azurecr.io/tops-rv/app:qa
        - environment: dev
          imageTagName: topsrvregistrydev.azurecr.io/tops-rv/app:dev
```
😇
