### ISSUE TITLE
volumeMounts with ReadOnlyMany seems to have ReadWrite privileges

### ISSUE THREAD

**Issue by ingeknudsen** [equinor/radix-platform#683]
**Describe the bug**
I mounted a `azure-blob` intending to read only. The script ran transformation of files into sub-folder (of the mounted folder) and that resulted in files written back to blob container

**To Reproduce**
Added to `radixconfig`:

```yaml
volumeMounts:
- type: azure-blob
    name: mounted-storage
    storage: processed
    path: /processed
    requestsStorage: 50Gi
    accessMode: ReadOnlyMany
```

Solution wrote to folder `/processed/.../.../transformed/`

**Expected behavior**
Error message in solution stating the folder is read only and that temporary files cannot be written to `/processed/.../...`

**Screenshots**
The following files comes from the solution, and should not have been there:
![Screenshot 2022-06-10 at 10 24 03](https://user-images.githubusercontent.com/10051649/173023936-69e3d2f9-1627-4de5-b569-4c9acfc49a1c.png)
