### ISSUE TITLE
Reference env variables from within radixconfig.yml

### ISSUE THREAD

**Issue by tkalve** [equinor/radix-platform#769]
**Is your feature request related to a problem? Please describe.**
I would like be able to change the oauth2 client id without updating radixconfig.yml manually with the new client id, ie. by having the client id together with the client secret in a keyvault.

**Describe the solution you'd like**
A way to reference environment variables and secrets within radixconfig.yaml
ie; 
```
components:
  - name: frontend
    secrets:
      - MY_CLIENT_ID
    authentication:
      oauth2:
        clientId: ${MY_CLIENT_ID} (referencing the secret declared above)
```
or 
```
components:
  - name: frontend
    secretRefs:
      azureKeyVaults:
        - name: radix-app-secrets
          path: /mnt/key-vault
          items:
            - name: frontend-client-id
              type: secret
              envVar: MY_CLIENT_ID
    authentication:
      oauth2:
        clientId: ${MY_CLIENT_ID} (referencing the keyvault secret declared above)
```

**Describe alternatives you've considered**
If it is not doable to reference the env vars from inside radix config, I suggest being able to add a different kind of parameter that can be referenced from yaml.
