### ISSUE TITLE
Environment card order is random in the frontend

### ISSUE THREAD

**Issue by v3gard** [equinor/radix-platform#793]
**Describe the bug**
Environment card order is random in the frontend. I expect the order to be identical between page refreshes, and it should be ordered as expressed in the radixconfig.yaml. E.g. 

```yaml
apiVersion: radix.equinor.com/v1
kind: RadixApplication
spec:
  environments:
    - name: ci
      build:
        from: main
    - name: qa
    - name: prod
```

|-|Example|
|-|-|
|1|![image](https://user-images.githubusercontent.com/343078/199707289-112b9d6f-4373-4cb5-8b4f-f2a49a80db7d.png)|
|2|![image](https://user-images.githubusercontent.com/343078/199707376-ac86c0ab-4fca-4924-ac45-daf93e4d4405.png)|

**To Reproduce**
1. Go to console -> Environments
2. Make note of the current order
3. Refresh the page
4. See that the order is not consistent

**Expected behavior**
Order is consistent with radixconfig.yaml file.

**Cluster**
- [x] Production EU
- [ ] Playground

**Additional context**
Relevant discussion on Slack: https://equinor.slack.com/archives/CBKM6N2JY/p1667390405507499
