### ISSUE TITLE
Use Cilium bring-your-own-CNI in a Radix cluster

### ISSUE THREAD

**Issue by magnus-longva-bouvet** [equinor/radix-platform#968]

**Comment by magnus-longva-bouvet** [comment]
Cluster `cilium-cni` is up and running. For some reason, the cluster seems unable to find a route to storage account `s941radixvelerodev`, which uses a Private Endpoint. IP is resolved correctly, but errors in hubble look like this

> May 10 16:03:10.717: velero/velero-6fc94dd8c5-n4mxp:57140 (ID:43402) <> 10.0.0.11:443 (world) Stale or unroutable IP DROPPED (TCP Flags: SYN)
> May 10 16:03:10.718: velero/velero-6fc94dd8c5-n4mxp:57140 (ID:43402) -> 10.0.0.11:443 (world) to-overlay FORWARDED (TCP Flags: SYN)

**Comment by nilsgstrabo** [comment]
Issues with routing to private endpoints resolved:

When using the default AKS network plugin, IP addresses for pods and nodes are assigned from the cluster's vnet CIDR range (e.g 10.7.0.0/18).
Private endpoint IP adresses are in a different vnet, with CIDR 10.0.0.0/18.
The cluster vnet and private endpoint vnet are peered.

Cilium use it's own CIDR range when assigning IP addresses to pods, and the default is 10.0.0.0/8. This range conflicts with the private endpoint vnet, and is the reason that pods could not connect to private endpoints.

When installing Cilium, we must chose a CIDR range for pods that does not conflict with the cluster vnet (IP for nodes) or the private endpoint vnet.

Example helm values (pod CIDR is defined in clusterPoolIPv4PodCIDRList):
```
nodeinit:
  enabled: true

aksbyocni:
  enabled: true

azure:
  resourceGroup: clusters

k8sClientRateLimit:
  qps: 20
  burst: 20

prometheus:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

operator:
  prometheus:
    enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.200.0.0/16"]
    clusterPoolIPv4MaskSize: 24
```
